#pragma once

// Convenience umbrella header for applications using Emerald.
#include "Emerald/Core/Defines.h"

#include "Emerald/Assets/Image.h"
#include "Emerald/Core/Application.h"
#include "Emerald/Core/FixedTimestep.h"
#include "Emerald/Core/Log.h"
#include "Emerald/Core/Paths.h"
#include "Emerald/Core/ThreadPool.h"
#include "Emerald/Core/Window.h"
#include "Emerald/Audio/Audio.h"
#include "Emerald/Audio/Mixer.h"
#include "Emerald/Audio/Sound.h"
#include "Emerald/Audio/Synth.h"
#include "Emerald/Input/Gamepads.h"
#include "Emerald/Input/Input.h"
#include "Emerald/Input/Keyboard.h"
#include "Emerald/Math/Math.h"
#include "Emerald/Memory/Memory.h"
#include "Emerald/Particles/ParticleSystem.h"
#include "Emerald/Renderer/Camera2D.h"
#include "Emerald/Renderer/CrtEffect.h"
#include "Emerald/Renderer/Font.h"
#include "Emerald/Renderer/Pipeline.h"
#include "Emerald/Renderer/Renderer.h"
#include "Emerald/Renderer/Renderer2D.h"
#include "Emerald/Renderer/Sprite.h"
#include "Emerald/Renderer/Texture.h"
#include "Emerald/Renderer/TextureAtlas.h"
#include "Emerald/Renderer/Shader.h"
